#!/usr/bin/env bash
# =============================================================================
# NixOS Hyprland workstation bootstrap
#
# Prerequisites:
#   1. Fresh NixOS install — boot from ISO and run:
#        nixos-generate-config --root /mnt
#        nixos-install
#        reboot
#   2. Log in, clone dotfiles:
#        nix-shell -p git --command "git clone <repo> ~/nodestack/dotfiles"
#   3. Run this script:
#        cd ~/nodestack/dotfiles && bash nixos/init.sh
#
# What this script does:
#   - Prompts for username / hostname / timezone
#   - Copies flake.nix + configuration.nix (with substitutions) to /etc/nixos/
#   - Enables Nix flakes
#   - Runs nixos-rebuild switch
#   - Creates all dotfiles symlinks
#   - Sets up TPM, neovim python, zsh default shell
# =============================================================================
set -euo pipefail

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NIXOS_DIR="$DOTFILES/nixos"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
symlink() {
    local src=$1 dst=$2
    mkdir -p "$(dirname "$dst")"
    rm -rf "$dst"
    ln -s "$src" "$dst"
    echo "  linked: $dst"
}

clone_if_missing() {
    local repo=$1 dest=$2
    if [[ ! -d "$dest" ]]; then
        git clone "$repo" "$dest"
    else
        echo "  already exists: $dest"
    fi
}

cmd_exists() { command -v "$1" &>/dev/null; }

header() { echo; echo "==> $*"; }

# ---------------------------------------------------------------------------
# Guard — must be on NixOS
# ---------------------------------------------------------------------------
if ! grep -q 'ID=nixos' /etc/os-release 2>/dev/null; then
    echo "ERROR: This script is for NixOS only."
    echo "       For Pop!_OS / macOS run the root init.sh instead."
    exit 1
fi

# ---------------------------------------------------------------------------
# Configuration — auto-detect where possible, cache timezone
# ---------------------------------------------------------------------------
header "Gathering configuration"

USERNAME="$(whoami)"
HOSTNAME="$(hostname)"

# Cache timezone so re-runs don't prompt again
TZ_CACHE="$DOTFILES/.nixos_timezone"
if [[ -f "$TZ_CACHE" ]]; then
    TIMEZONE="$(cat "$TZ_CACHE")"
    echo "  Timezone : $TIMEZONE (cached — delete .nixos_timezone to change)"
else
    read -rp "  Timezone [America/Toronto]: " INPUT_TZ
    TIMEZONE="${INPUT_TZ:-America/Toronto}"
    echo "$TIMEZONE" > "$TZ_CACHE"
fi

echo "  Username : $USERNAME"
echo "  Hostname : $HOSTNAME"
echo "  Timezone : $TIMEZONE"

# ---------------------------------------------------------------------------
# Flakes are enabled via configuration.nix (nix.settings.experimental-features)
# — no need to touch /etc/nix/nix.conf (read-only on NixOS)
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Copy NixOS config to /etc/nixos/
# ---------------------------------------------------------------------------
header "Setting up /etc/nixos"

# Preserve hardware-configuration.nix generated by nixos-generate-config
if [[ ! -f /etc/nixos/hardware-configuration.nix ]]; then
    echo "ERROR: /etc/nixos/hardware-configuration.nix not found."
    echo "       Run: sudo nixos-generate-config"
    exit 1
fi

echo "  Copying flake.nix"
sudo cp "$NIXOS_DIR/flake.nix" /etc/nixos/flake.nix

echo "  Copying configuration.nix (substituting placeholders)"
sudo cp "$NIXOS_DIR/configuration.nix" /etc/nixos/configuration.nix

sudo sed -i "s/YOUR_USERNAME/$USERNAME/g" /etc/nixos/configuration.nix
sudo sed -i "s/YOUR_HOSTNAME/$HOSTNAME/g" /etc/nixos/configuration.nix
sudo sed -i "s|YOUR_TIMEZONE|$TIMEZONE|g"  /etc/nixos/configuration.nix

echo "  Done — /etc/nixos/:"
ls /etc/nixos/

# ---------------------------------------------------------------------------
# nixos-rebuild switch
# ---------------------------------------------------------------------------
header "Running nixos-rebuild switch (this will take a while on first run)"
sudo nixos-rebuild switch 2>&1 | tee /tmp/nixos-rebuild.log || {
    echo
    echo "ERROR: nixos-rebuild failed. Check /tmp/nixos-rebuild.log"
    exit 1
}

# ---------------------------------------------------------------------------
# Dotfiles symlinks
# ---------------------------------------------------------------------------
header "Creating dotfiles symlinks"

# Shell
symlink "$DOTFILES/shell/zsh/my_aliases.sh"  "$HOME/.my_aliases.sh"
symlink "$DOTFILES/shell/zsh/zshrc"          "$HOME/.zshrc"

# Prompt
symlink "$DOTFILES/shell/prompt/ohmyposh"    "$HOME/.config/ohmyposh"

# Editor
symlink "$DOTFILES/editors/nvim"             "$HOME/.config/nvim"

# Terminal
symlink "$DOTFILES/terminal/wezterm/wezterm.lua" "$HOME/.wezterm.lua"
symlink "$DOTFILES/terminal/zellij"          "$HOME/.config/zellij"
symlink "$DOTFILES/terminal/kitty"           "$HOME/.config/kitty"

# Hyprland ecosystem
symlink "$NIXOS_DIR/config/hypr"             "$HOME/.config/hypr"

# Waybar
symlink "$NIXOS_DIR/config/waybar"           "$HOME/.config/waybar"

# Mako notifications
symlink "$NIXOS_DIR/config/mako"             "$HOME/.config/mako"

# Wofi launcher
symlink "$NIXOS_DIR/config/wofi"             "$HOME/.config/wofi"

# Wallpapers
mkdir -p "$HOME/Pictures"
symlink "$DOTFILES/wallpapers" "$HOME/Pictures/Wallpapers"

# Screenshots directory
mkdir -p "$HOME/Pictures/Screenshots"

# ---------------------------------------------------------------------------
# Tmux Plugin Manager
# ---------------------------------------------------------------------------
header "Tmux Plugin Manager"
clone_if_missing "https://github.com/tmux-plugins/tpm" "$HOME/.tmux/plugins/tpm"

# ---------------------------------------------------------------------------
# Default shell → zsh
# ---------------------------------------------------------------------------
header "Setting default shell to zsh"
ZSH_PATH="$(command -v zsh)"
if [[ "$SHELL" != "$ZSH_PATH" ]]; then
    if ! grep -q "$ZSH_PATH" /etc/shells; then
        echo "$ZSH_PATH" | sudo tee -a /etc/shells
    fi
    chsh -s "$ZSH_PATH" "$USERNAME"
    echo "  Default shell set to $ZSH_PATH"
else
    echo "  Already using zsh"
fi

# ---------------------------------------------------------------------------
# Neovim Python support
# ---------------------------------------------------------------------------
header "Neovim Python support"
if cmd_exists pip3; then
    pip3 install --user pynvim neovim 2>/dev/null || true
    echo "  pynvim installed"
else
    echo "  pip3 not found — skipping (pynvim is in system packages)"
fi

# ---------------------------------------------------------------------------
# Cliphist daemon (start for current session if not running)
# ---------------------------------------------------------------------------
header "Clipboard history daemon"
if ! pgrep -x cliphist &>/dev/null; then
    nohup wl-paste --watch cliphist store &>/dev/null &
    echo "  cliphist daemon started"
else
    echo "  cliphist already running"
fi

# ---------------------------------------------------------------------------
# Wallpaper reminder
# ---------------------------------------------------------------------------
echo
echo "┌─────────────────────────────────────────────────────────┐"
echo "│  Setup complete!                                        │"
echo "│                                                         │"
echo "│  Next steps:                                            │"
echo "│  1. Launch Hyprland:                                    │"
echo "│       Hyprland                                          │"
echo "│     (or reboot to use the greetd login screen)          │"
echo "│                                                         │"
echo "│  2. Inside Hyprland, open Neovim and run :Lazy sync     │"
echo "│                                                         │"
echo "│  Wallpapers: ~/Pictures/Wallpapers/                     │"
echo "│    default → quasar.webp                                │"
echo "└─────────────────────────────────────────────────────────┘"
echo
